### ISSUE TITLE
Api changed

### ISSUE THREAD

**Issue by tkleijkers** [barcar/visonic_control#3]
The API has changed so login does not work anymore. Do you have any idea how the new API works?

**Comment by barcar** [comment]
No. I don’t. I’ll take a look but not sure how quickly I will get to it.

**Comment by barcar** [comment]
I just ran a Charles Proxy session with the new app and, as far as I can tell, they are now using SSL pinning which means I can't intercept the API calls with Charles. I've not given up but it's not going to be as easy as it was before.

**Comment by barcar** [comment]
I couldn't figure out what changed by myself but I think this person has... https://github.com/And3rsL/VisonicAlarm2. Their commits reference upgrading to API v8 which is what I see listed at https://visonic.tycomonitor.com/rest_api/version = so maybe there is hope. I'm going to archive this project since others are doing it better.
